### ISSUE TITLE
Split out GraphiQL as separate plug

### ISSUE THREAD

**Issue by joshprice** [joshprice/hello_graphql_phoenix#10]
GraphiQL is unlikely to be deployed in prod (by default), but should be on in other environments.

It should be separated out from the Endpoint plug and configurable on it's own.

This affects #5

**Comment by aweiker** [comment]
Shouldn't this issue be in joshprice/plug_graphql

**Comment by joshprice** [comment]
Yep :derp:

**Comment by joshprice** [comment]
Closing, duplicate of https://github.com/joshprice/plug_graphql/issues/16
